### ISSUE TITLE
missing json issue!!

### ISSUE THREAD

**Issue by ghost** [MarcBotet/hamlet#10]
Hi, when I try to run the Python run_experiments.py—-exp -1 --wandb 1 command, I get the following missing json issue!!

fatal: not a git repository (or any of the parent directories): .git
Run job 240513_1502_cs2rain_dacs_online_rcs001_cpl_segformer_mitb1_fixed_s0_13b23
job number 0
Traceback (most recent call last):
  File "run_experiments.py", line 152, in <module>
    train.main([config_files[i]])
  File "D:\PhD\code03-Pt2\To Adapt or Not to Adapt Real-Time Adaptation for Semantic Segmentation\hamlet-main\tools\train.py", line 113, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "C:\Users\PHY3BOHORT\Anaconda3\Lib\site-packages\mmcv\utils\config.py", line 468, in dump
    mmcv.dump(cfg_dict, file)
  File "C:\Users\PHY3BOHORT\Anaconda3\Lib\site-packages\mmcv\fileio\io.py", line 80, in dump
    handler.dump_to_path(obj, file, **kwargs)
  File "C:\Users\PHY3BOHORT\Anaconda3\Lib\site-packages\mmcv\fileio\handlers\base.py", line 24, in dump_to_path
    with open(filepath, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'work_dirs\\local-exp-1\\240513_1502_cs2rain_dacs_online_rcs001_cpl_segformer_mitb1_fixed_s0_13b23\\240513_1502_cs2rain_dacs_online_rcs001_cpl_segformer_mitb1_fixed_s0_13b23.json

**Comment by MarcBotet** [comment]
When you run with exp -1 it should save the config file in `work_dirs\local-exp-1` this happens in run_experiments.py in l. 142. This is the file is missing. It should be working, so the best I can tell you is to make sure that the folders exist and the file is saved properly.
